name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Hydra
        run: |
          mkdir -p "$HOME/.hydra"
          cp -R . "$HOME/.hydra"
          echo "alias hydra='bash \"$HOME/.hydra/hydra.sh\"'" >> "$HOME/.bashrc"

      - name: Run Hydra Tests
        run: |
          source "$HOME/.bashrc"
          hydra test
